apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8update
spec:
  schedule: "@hourly"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 360
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8update
          containers:
          - name: k8update
            image: ghcr.io/chrisns/k8update
          restartPolicy: OnFailure
