name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.2.1
        with:
          images: docker.pkg.github.com/chrisns/k8update/k8update
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          label-custom: |
            org.opencontainers.image.vendor=chrisns
            org.opencontainers.image.documentation=https://github.com/chrisns/k8update
            org.opencontainers.image.authors=Chris Nesbitt-Smith <chris@cns.me.uk>
            maintainer=chrisns
      - name: Login to docker registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
